apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test1
  description: test1
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]